### PR TITLE
code splitting: include all libraries in vendor.js

### PR DESCRIPTION
**Pull request by mastilver**

### CODE REVIEW

**Comment by rstacruz** [comment]
@havenchyk any reason you gave a thumbs down?

**Comment by rstacruz** [comment]
This is actually pretty damn neat. I haven't tried it yet though.

**Comment by havenchyk** [comment]
@rstacruz @mastilver 

Well, put every module from `node_modules` to `vendor` is not a good practice from caching perspective. 

I agree with your initial version, when you explicitly mark which modules you would like to put to `vendor.js`, but regarding all the `node_modules` it's not a good advice. You know every update of somepackagefromnodemodules will lead to re-download, re-parse, re-cache for end user.

But if you know which modules will be in `vendor.js`, it's much better for you as for developer and for end user.

So this change is not really helpful, that's why I downvoted it.

But it's just my opinion

Update:
A suggested approach is fine for small projects with few dependencies, but it's usual to have a lot of dependencies for every small piece of functionality nowadays

**Comment by rstacruz** [comment]
:point_up: I agree, my thoughts as well. I think this can be in the guide as a separate section; the explicit version is more reasonable and deserves to stay IMHO.

**Comment by havenchyk** [comment]
Great, basically it's a good trick, when developer understands what's going on, so it's worth to have it mentioned, but with some explanation, that for big projects with a lot of dependencies it's not really helpful

**Comment by mastilver** [comment]
As @bfred-it said on https://github.com/rstacruz/webpack-tricks/issues/5#issuecomment-268759624
> Yes but how do you track those changes? Webpack still rebuilds that file and its modified time changes. While you think it's not being downloaded, it most likely still is.

Your `vendor.js` is still likely to be re-downloaded every time you run webpack (this is happening on my system)

The first reason I'm doing this is to reduce build time when I'm using webpack on watch mode

------

Although, I don't mine modifying this PR is keep the previous version and add the one with all libs on another section

**Comment by havenchyk** [comment]
@mastilver you know, maybe I was wrong and your advice is nice 😄

**Comment by oieduardorabelo** [comment]
I didn't know this trick, in a few cases is awesome (I'm already changing a few projects =P),

imo, worth to be mentioned!

**Comment by oieduardorabelo** [comment]
do you guys think that can work with multiple CommonsChunkPlugin?

I'm trying/debugging the following:


```
  entry: {
    app: './client/app.jsx',
  },
  output: {
    path: './dist',
    filename: '[name].bundle.js',
  },
  plugins: [
    new webpack.optimize.CommonsChunkPlugin({
      name: 'admin',
      minChunks: ({ resource }) => {
        if (/client\/admin/.test(resource)) {
          console.log('Admin', resource)
          return true
        }
      }
    }),
    new webpack.optimize.CommonsChunkPlugin({
      name: 'dashboard',
      minChunks: ({ resource }) => {
        if (/client\/dashboard/.test(resource)) {
          console.log('Dashboard', resource)
          return true
        }
      }
    }),
    new webpack.optimize.CommonsChunkPlugin({
      name: 'settings',
      minChunks: ({ resource }) => {
        if (/client\/settings/.test(resource)) {
          console.log('Settings', resource)
          return true
        }
      }
    }),
    new webpack.optimize.CommonsChunkPlugin({
      name: 'vendor',
      minChunks: ({ resource }) => {
        if (/node_modules/.test(resource)) {
          console.log('Vendor', resource)
          return true
        }
      }
    }),
  ],
```

but seems just the first one runs :( cc @mastilver

**Pull request closed without merging**
